# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Record": "00_core.ipynb",
         "Lesson": "00_core.ipynb",
         "Subject": "00_core.ipynb",
         "Program": "00_core.ipynb",
         "fullPathSplit": "01_StudySystem.ipynb",
         "PathValidaor": "01_StudySystem.ipynb",
         "lessonsFromDirectory": "01_StudySystem.ipynb",
         "subjectFromPath": "01_StudySystem.ipynb",
         "sample": "01_StudySystem.ipynb",
         "testS": "01_StudySystem.ipynb",
         "StudySystem": "01_StudySystem.ipynb",
         "cleanLesson": "02_DataMunge.ipynb",
         "makePriorsForSubject": "02_DataMunge.ipynb",
         "Render": "05_staticGenerator.ipynb"}

modules = ["Program.py",
           "School.py",
           "munge.py",
           "flask.py",
           "Web.py"]

doc_url = "https://arthurconner.github.io/refreshment/"

git_url = "https://github.com/arthurconner/refreshment/tree/master/"

def custom_doc_links(name): return None
