# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Record": "00_core.ipynb",
         "Lesson": "00_core.ipynb",
         "Subject": "00_core.ipynb",
         "Program": "00_core.ipynb",
         "fullPathSplit": "01_StudySystem.ipynb",
         "PathValidaor": "01_StudySystem.ipynb",
         "lessonsFromDirectory": "01_StudySystem.ipynb",
         "subjectFromPath": "01_StudySystem.ipynb",
         "sample": "01_StudySystem.ipynb",
         "testS": "01_StudySystem.ipynb",
         "StudySystem": "01_StudySystem.ipynb",
         "removeAuthor": "02_DataMunge.ipynb",
         "cleanName": "02_DataMunge.ipynb",
         "cleanLesson": "02_DataMunge.ipynb",
         "subjectWithName": "02_DataMunge.ipynb",
         "assignLessonsWithName": "02_DataMunge.ipynb",
         "makePriorsForSubject": "02_DataMunge.ipynb",
         "unassignedForSubject": "02_DataMunge.ipynb",
         "printAllUnassigned": "02_DataMunge.ipynb",
         "filePathForMeta": "02_DataMunge.ipynb",
         "assignCategoriesToSubject": "02_DataMunge.ipynb",
         "loadMetaFile": "02_DataMunge.ipynb",
         "writeMetaFile": "02_DataMunge.ipynb",
         "processGuide": "02_DataMunge.ipynb",
         "initials": "02_DataMunge.ipynb",
         "keyFromDate": "02_DataMunge.ipynb",
         "dataFromDate": "02_DataMunge.ipynb",
         "dateGrid": "02_DataMunge.ipynb",
         "Render": "03_StaticGenerator.ipynb",
         "makeSite": "03_StaticGenerator.ipynb"}

modules = ["Program.py",
           "School.py",
           "Munge.py",
           "Web.py",
           "covid.py"]

doc_url = "https://arthurconner.github.io/refreshment/"

git_url = "https://github.com/arthurconner/refreshment/tree/master/"

def custom_doc_links(name): return None
