# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_DataMunge.ipynb (unless otherwise specified).

__all__ = ['cleanLesson', 'makePriorsForSubject']

# Cell
import os
import sys
import pandas as pd
import re
from time import gmtime, strftime, ctime
from datetime import datetime, timedelta
from collections import defaultdict

# Cell
from .School import StudySystem,subjectFromPath
from .Program import Program, Subject, Record, Lesson

# Cell

def cleanLesson(less):
    for l in less.lessons:

        label = re.sub(r'((?<=[a-z])[A-Z]|(?<!\A)[A-Z](?=[a-z]))', r' \1', l.fileName)
        if label[-4] == ".":
            label = label[:-4]
        label = re.sub(' +', ' ', label)
        if l.name == l.fileName:
            l.name = label



# Cell
def makePriorsForSubject(sub):
    skips = {}
    for (key, seq) in sub.sequences.items():
        i = 0
        for x in seq:
            less = sub.lookup[x]
            less.prior = seq[:i]
            less.next = seq[i+1:]
            i += 1
            skips[x] = 1

    unassigned = [x.key for x in sub.lessons if not x.key in skips]
    i = 0
    for x in unassigned:
        less = sub.lookup[x]
        less.prior = unassigned[:i]
        less.next = unassigned[i+1:]
        i += 1

