# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_DataMunge.ipynb (unless otherwise specified).

__all__ = ['cleanLesson']

# Cell
import os
import sys
import pandas as pd
import re
from time import gmtime, strftime, ctime
from datetime import datetime, timedelta
from collections import defaultdict

# Cell
from .School import StudySystem,subjectFromPath
from .Program import Program, Subject, Record, Lesson

# Cell

def cleanLesson(less):
    for l in less.lessons:

        label = re.sub(r'((?<=[a-z])[A-Z]|(?<!\A)[A-Z](?=[a-z]))', r' \1', l.fileName)
        if label[-4] == ".":
            label = label[:-4]
        label = re.sub(' +', ' ', label)
        if l.name == l.fileName:
            l.name = label

